#!/bin/bash
# postinst script
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)

        mkdir -p /etc/perfsonar/psconfig/grafana.d/
        chown perfsonar:perfsonar /etc/perfsonar/psconfig/grafana.d/
        mkdir -p /var/lib/perfsonar/psconfig/grafana_template_cache
        chown perfsonar:perfsonar /var/lib/perfsonar/psconfig/grafana_template_cache
        # Ensure correct permissions on config file for both new installs and upgrades
        if [ -f /etc/perfsonar/psconfig/grafana-agent.json ]; then
            chmod 0600 /etc/perfsonar/psconfig/grafana-agent.json
            chown perfsonar:perfsonar /etc/perfsonar/psconfig/grafana-agent.json
        fi
        # check if installation or update, where version is a parameter
        if [ -z "$2" ]; then

            #Enable service on new install
            systemctl daemon-reload  || :
            systemctl enable psconfig-grafana-agent.service  || :
        fi
        systemctl start psconfig-grafana-agent.service  || :
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
exit 0