#!/bin/bash
# postinst script for perfsonar-grafana
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        mkdir -p /etc/perfsonar/psconfig/pscheduler.d/
        chown perfsonar:perfsonar /etc/perfsonar/psconfig/pscheduler.d/
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
exit 0