#!/bin/sh

set -e

service psconfig-maddash-agent status

pgrep -fl psconfig_maddash_agent

psconfig agents | grep -C 10 MaDDash

psconfig remote list | grep -C 10 '^\['

psconfig maddash-stats | grep -C 10 'PID.*[[:digit:]]\+$'

psconfig maddash-grid list | grep -C 10 '^{'

psconfig maddash-viz-plugins | grep ^ps-

psconfig maddash-check-plugins | grep ^ps-
