#!/bin/sh

set -e

service psconfig-pscheduler-agent status

pgrep -fl psconfig_pscheduler_agent

psconfig agents | grep -C 10 pScheduler

psconfig remote list | grep -C 10 '^\['

psconfig pscheduler-stats | grep -C 10 'PID.*[[:digit:]]\+$'

psconfig pscheduler-tasks | grep -C 10 '^{'
