etc/maddash-agent.json etc/perfsonar/psconfig
etc/maddash-agent-logger.conf etc/perfsonar/psconfig
bin/psconfig_maddash_agent usr/lib/perfsonar/bin
bin/psconfig_commands/maddash-* usr/lib/perfsonar/bin/psconfig_commands/
lib/perfSONAR_PS/PSConfig/MaDDash/* usr/lib/perfsonar/lib/perfSONAR_PS/PSConfig/MaDDash/
lib/perfSONAR_PS/PSConfig/CLI/MaDDash.pm usr/lib/perfsonar/lib/perfSONAR_PS/PSConfig/CLI/
scripts/psconfig-maddash-agent.service lib/systemd/system
