etc/pscheduler-agent.json etc/perfsonar/psconfig
etc/pscheduler-agent-logger.conf etc/perfsonar/psconfig
bin/psconfig_pscheduler_agent usr/lib/perfsonar/psconfig/bin
bin/psconfig_commands/pscheduler-* usr/lib/perfsonar/psconfig/bin/psconfig_commands/
scripts/psconfig-pscheduler-agent.service lib/systemd/system
lib/perfSONAR_PS/PSConfig/PScheduler/* usr/lib/perfsonar/psconfig/lib/perfSONAR_PS/PSConfig/PScheduler/
